### ISSUE TITLE
YUV 4:0:0是否就是灰度图呢？

### ISSUE THREAD

**Issue by Sjunhao** [ZoengMingWong/BM3D_step1_cpp#1]
感谢您的贡献。
我想问一下YUV4：0：0的图是否就是单通道的灰度图呢？
我是否可以输入一个类型为char[]图 并将chanel设置为1，用以处理单通道灰度图?因为关于YUV4:0:0的资料太少了。
如果不是，我将如何更改代码实现对灰度图的处理呢？感谢

**Comment by ZoengMingWong** [comment]
抱歉，没留意到问题，希望你已经解决。是的，YUV400 主要是统一说法而已，Y 就是亮度分量，和灰度的概念是相同，: 0 : 0 表示 U 和 V 的采样率为 0，所以就不包含色度分量了。你要跑灰度图只要把 chnl 改为 1，代码里除了图像尺寸和文件路径，也基本不需要改动了。
